spring:
  application:
    name: citizen-api
  
  datasource:
    url: jdbc:h2:mem:citizendb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false # Disabled for Phase 1 as we haven't created migration scripts yet

server:
  port: 8080
